---
- name: Nginx Webserver
  hosts: all
  vars:
    ansible_ssh_user: 'vagrant'
    ansible_ssh_private_key_file: 'vagrant.priv'
    ansible_port: '2222'
    ansible_python_interpreter: '/usr/bin/python'

  tasks:
  - shell: whoami
    register: foo
  - debug: msg="username saya adalah {{ foo.stdout }}"

  - name: Start Nginx
    service:
      name: nginx
      state: started