---
- name: Ping Test
  hosts: all
  vars:
    ansible_ssh_user: 'vagrant'
    # ansible_password: 'vagrant'
    ansible_ssh_private_key_file: 'vagrant.priv'
    ansible_port: '2222'
    ansible_python_interpreter: '/usr/bin/python2'

  tasks:
  - ping: